'''
Per-image Dice comparison for the CLAHE k0 pilot vs. the existing official
baseline k0, restricted to the 43-image cross-network overlap set
(per_image_analysis_v2/cross_network_overlap_ids.csv) -- the images where
BOTH SwinUnet and AViT baseline models scored Dice < 0.5, i.e. the taxonomy's
proposed shared-failure set that CLAHE (contrast enhancement) is meant to fix.

Baseline per-image dice for these IDs is read from the existing
train_{network}_baseline.csv / test_{network}_baseline.csv (already cover
all 2600 official images, generated by rebuild_taxonomy_full.py). CLAHE
per-image dice is computed fresh here by running each new CLAHE k0
checkpoint on just these 43 images (image_subdir=Image_clahe), matching
rebuild_taxonomy_full.py's inference method exactly (batch_size=1, medpy dc
@ 0.5) so the two are directly comparable.

Run only after both isic2017_{swinunet,avit}_clahe_k0 checkpoints exist.
'''
import glob
import os
import pandas as pd
import torch
import medpy.metric.binary as metrics

from Datasets.create_dataset import SkinDataset_csv
from Models.Transformer.SwinUnet import SwinUnet
from Models.Transformer.Swin_adapters import SwinSimpleSeg_CNNprompt_adapt

ROOT = 'C:/Users/quanp/Downloads/ISIC 2017'
DATA_PATH = ROOT + '/data/isic2017/'
PRETRAINED_FOLDER = ROOT + '/pretrained_ckpt'
ANALYSIS_DIR = ROOT + '/per_image_analysis_v2'
IMG_SIZE = 224

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


def find_ckpt(pattern):
    matches = sorted(glob.glob(os.path.join(ROOT, 'results', pattern, 'best.pth')))
    if not matches:
        raise FileNotFoundError('No checkpoint matching {}'.format(pattern))
    return matches[-1]  # most recent if more than one


def build_model(network, ckpt):
    if network == 'SwinUnet':
        model = SwinUnet(img_size=IMG_SIZE)
    else:
        model = SwinSimpleSeg_CNNprompt_adapt(
            img_size=IMG_SIZE, pretrained=False, pretrained_swin_name='swin_large_patch4_window7_224_22k',
            pretrained_folder=PRETRAINED_FOLDER, embed_dim=192, drop_path_rate=0.2,
            depths=[2, 2, 18], num_heads=[6, 12, 24], window_size=7,
            debug=False, adapt_method=False, num_domains=1,
        )
    model.load_state_dict(torch.load(ckpt, map_location=device))
    model.to(device).eval()
    return model


def run_inference(model, network, df, image_subdir):
    ds = SkinDataset_csv('isic2017', IMG_SIZE, df, use_aug=False, data_path=DATA_PATH, image_subdir=image_subdir)
    loader = torch.utils.data.DataLoader(ds, batch_size=1, shuffle=False, num_workers=0)
    records = []
    with torch.no_grad():
        for batch in loader:
            img_id = batch['ID'][0]
            img = batch['image'].to(device).float()
            label = (batch['label'].to(device).float().cpu().numpy() > 0.5)
            if network == 'SwinUnet':
                output = torch.sigmoid(model(img))
            else:
                output = torch.sigmoid(model(img, d='0')['seg'])
            pred = (output.cpu().numpy() > 0.5)
            dice = metrics.dc(pred, label)
            records.append({'image_id': img_id, 'dice_score': dice})
    return pd.DataFrame(records)


def main():
    overlap_ids = pd.read_csv(os.path.join(ANALYSIS_DIR, 'cross_network_overlap_ids.csv'), dtype={'image_id': str})
    overlap_set = set(overlap_ids['image_id'])
    print('{} overlap IDs loaded'.format(len(overlap_set)))

    meta = pd.read_csv(DATA_PATH + 'meta_isic2017.csv', dtype={'ID': str})
    df43 = meta[meta['ID'].isin(overlap_set)].reset_index(drop=True)
    assert len(df43) == len(overlap_set), 'meta_isic2017.csv missing {} of the overlap IDs'.format(
        len(overlap_set) - len(df43))

    train_ids = set(pd.read_csv(DATA_PATH + 'meta_isic2017_train2000.csv', dtype={'ID': str})['ID'])
    split_of = {i: ('train' if i in train_ids else 'test') for i in overlap_set}

    configs = [
        ('SwinUnet', 'swinunet', 'isic2017_swinunet_clahe_k0_SwinUnet_*'),
        ('AViT', 'avit', 'isic2017_avit_clahe_k0_SwinSeg_CNNprompt_adapt_*'),
    ]

    all_rows = []
    for network, key, ckpt_pattern in configs:
        ckpt = find_ckpt(ckpt_pattern)
        print('=== {} : {} ==='.format(network, ckpt))
        model = build_model(network, ckpt)
        clahe_df = run_inference(model, network, df43, 'Image_clahe')
        del model
        torch.cuda.empty_cache()

        base_train = pd.read_csv(os.path.join(ANALYSIS_DIR, 'train_{}_baseline.csv'.format(key)), dtype={'image_id': str})
        base_test = pd.read_csv(os.path.join(ANALYSIS_DIR, 'test_{}_baseline.csv'.format(key)), dtype={'image_id': str})
        base_all = pd.concat([base_train, base_test], ignore_index=True)
        base43 = base_all[base_all['image_id'].isin(overlap_set)][['image_id', 'dice_score']].rename(
            columns={'dice_score': 'baseline_dice'})

        merged = clahe_df.rename(columns={'dice_score': 'clahe_dice'}).merge(base43, on='image_id', how='left')
        merged['network'] = network
        merged['split'] = merged['image_id'].map(split_of)
        merged['delta'] = merged['clahe_dice'] - merged['baseline_dice']
        all_rows.append(merged)

    result = pd.concat(all_rows, ignore_index=True)[
        ['network', 'image_id', 'split', 'baseline_dice', 'clahe_dice', 'delta']]
    out_path = os.path.join(ANALYSIS_DIR, 'clahe_vs_baseline_overlap43.csv')
    result.to_csv(out_path, index=False)
    print('Saved {} ({} rows)'.format(out_path, len(result)))

    for network in ['SwinUnet', 'AViT']:
        sub = result[result['network'] == network]
        n_improved = (sub['delta'] > 0.01).sum()
        n_worse = (sub['delta'] < -0.01).sum()
        n_flat = len(sub) - n_improved - n_worse
        print('\n=== {} on the 43 overlap images ===' .format(network))
        print('  mean baseline dice: {:.4f}'.format(sub['baseline_dice'].mean()))
        print('  mean clahe dice:    {:.4f}'.format(sub['clahe_dice'].mean()))
        print('  mean delta:         {:+.4f}'.format(sub['delta'].mean()))
        print('  improved (>+0.01): {}, worse (<-0.01): {}, ~flat: {}'.format(n_improved, n_worse, n_flat))


if __name__ == '__main__':
    main()
